travis:
  secure:
    BINSTAR_TOKEN: 1aekrvjAnRARW/QNaFa2MxdLOavdRmGpRsRs0dkEmG1BTVlVNxdgcHRDQrNtsfOLnla5CKneuBEcoOZ60ZeJrKhpjTjwTF7GdyYJn8sI4atGlW+7t54O8oMlJBIJo9O4dtM+cfIiydrE41Gsjmd2q2U/N36Wj+eAWzU0yDU2/GWQq8Ber7c6xtbQhnMl7Kzy2LO16rnsNxWTv0pB7dQu5KSkY5mpXpDR8CQUwfDfEGB3ldOwYLMyNf85nr+6AIQiUUbAwHzNbOZGNAKrgfA6jvYtOIheKeZqN54KsOM0IohqAeZ8A/fI2ucSbaqa+WH6uBgpKe33Egu+/W1FRNuIaj+JioMGPkjZI1a6kp4QZtf84FcfE3NzrCiN6cRqkvyddcNclfigrwtV7/SLz1M3QHKkGwLCU/+90lIW0G98mVjnsaxya2sPYWb2BfuyduGNESm5CyUqV9j5qpdG2LF+K637W9vaydo3pRGTWMCkfj4l9zY58+UCmxZqdC8dFLRHdQG9OCWolkNIakfPWomh4jNPbbu2RonwjsGVkO9HO0eI/ooeAep07E8S6JFL4mJuf1lckut6rz33Yva1DR09BTOtDwTNMO47rQ4H9yBfFbA/OvUWyhgB9qcwroIR7rhx0QuYw3yeIV++rwKI6fnqPb3iMpM6hv6xkTZl8nOEx6w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
