appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: a+n+iFUwEzLA4WZQIQON9g5/jB0Kn1ZZRGFnwB7jbNsMgGkRNcNKN4MUdTOUNBRB3qAohqRGUhEBc404FZYEYB9ghrXvCxf4UIR3Mp+WMHh3w9JwIo+5ZwmjGCqwGqovrfvek4GIyX3o6rIg8Xfc6+I0+/eiL4hbhPTE6+xR7PdvYgPZfd0XZJncMZilg6xMGgHYpQEvkmaDVkCj2HUXj8ZgBrWmG5wrLZ9b8Bj4+EGI+RhmOZ86F/XAWbrSN55khHUd/ZlphmzmZ8bxkliOoyqe3ytcNORa7T6ag29ProO2LfToIwFHz6VRl5Nh12k156q4yZO7ew5kYxqkEHbYB3iVXdd79N0DhUg4SDgfoiaqSZNwxnk8Is8znUVcn3iARcGLe+upHBY+yi8zUFjQXO1woRtIbUkCvY9vCCfYTb1/O3fE/3OP7AdmxeDij329130r/2lgPMr57lqEAGFL7AugIdq2yNAcgWL4vEAdbrv/Zni03dl5cizdyMy7JV+i4pR8asyomBpU40pD3u6g5PAQs5hxxfBQroz9Au3Cm5Dd1a9jbFbv2SsQctUHtebnl8qQdwrLekjjKjTUN6mLYByJpUY4BVSFOzGa3artwYRtHI5fjLkNuP+EV/FDme6HCqshZe8gwk73gOBU3jEcLOkojU0IGi86gXg6KhDFVfs=}
